global:
  scrape_interval: 15s
  evaluation_interval: 1m

# Fichiers de règles d'alertes
rule_files:
  - /etc/prometheus/alerts.yml

# Configuration Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Scraper le Pushgateway pour les jobs cron et le scraping
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  # Scraper le node-exporter pour les métriques système
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Scraper cAdvisor pour les métriques des containers Docker
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
