"""Ajout des colonnes max, min et target à Stock

Revision ID: 7d29813a6974
Revises: 55bed6705752
Create Date: 2025-03-24 09:31:49.490211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d29813a6974'
down_revision = '55bed6705752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_column('target_price')
        batch_op.drop_column('min_price')
        batch_op.drop_column('max_price')

    # ### end Alembic commands ###
