{
 "title": "Datascientest System Monitoring",
 "tags": [ "alerts" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_load1 / on (job, instance) count(node_cpu_seconds_total{mode=\"idle\"})  by(job, instance) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (instance,mode)",
     "legendFormat": "{{instancve}}{{mode}}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Free RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Virtual Mem Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\r\n  node_filesystem_avail_bytes{mountpoint=\"/\", fstype!~\"tmpfs|squashfs|overlay\"}\r\n  / on(instance, device, mountpoint) node_filesystem_size_bytes{mountpoint=\"/\", fstype!~\"tmpfs|squashfs|overlay\"}\r\n)\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Free Memory (RAM + Swap)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes + node_memory_SwapFree_bytes)/( node_memory_MemTotal_bytes + node_memory_SwapTotal_bytes)*100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}